In [162]:
import requests
import pandas as pd
import spacy
import numpy as np

nlp = spacy.load('en')
headers = {'x-api-key': 'ORvogDjaqG5JoQJuCfV9LrGPOaB84EpirEz3GF2P'}

def url_to_call(url):
    mercury='https://mercury.postlight.com/parser?url='
    total_url = '{0}{1}'.format(mercury, url)
    call = requests.get(total_url, headers=headers)
    
    return call

In [163]:
data=pd.read_excel('/users/riya/documents/Coding/WT_Masterlist.xlsx')
clean=pd.DataFrame(data)
clean

,domain_url,Tier,Notes,Exact Match?
0,https://www.entrepreneur.com/,1,ADDED TO TW 8/1/16,No
1,https://next.ft.com/,1,ADDED TO TW 8/1/16,No
2,http://yahoo.com/,1,ADDED TO TW 8/1/16,No
3,http://www.worth.com/,1,ADDED TO TW 8/1/16,No
4,http://www.thinkadvisor.com/investment-advisor,1,ADDED TO TW 8/1/16,Yes
5,http://www.kiplinger.com/,1,ADDED TO TW 8/1/16,No
6,http://www.institutionalinvestor.com/,1,ADDED TO TW 8/1/16,No
7,http://www.inc.com/,1,ADDED TO TW 8/1/16,No
8,http://www.foxbusiness.com/,1,ADDED TO TW 8/1/16,No
9,http://www.fa-mag.com/private-wealth,1,ADDED TO TW 8/1/16,Yes
10,http://www.fa-mag.com/,1,ADDED TO TW 8/1/16,No
11,http://www.crainswealth.com/,1,ADDED TO TW 8/1/16,No
12,http://www.barrons.com/,1,ADDED TO TW 8/1/16,No
13,http://wsj.com/,1,ADDED TO TW 8/1/16,No
14,http://wsj.com/,1,ADDED TO TW 8/1/16,No
15,http://wealthmanagement.com/te-home,1,ADDED TO TW 8/1/16,Yes
16,http://wealthmanagement.com/,1,ADDED TO TW 8/1/16,No
17,http://washingtonpost.com/,1,ADDED TO TW 8/1/16,No
18,http://usnews.com,1,ADDED TO TW 8/1/16,No
19,http://usatoday.com/,1,ADDED TO TW 8/1/16,No
20,http://time.com/money/,1,ADDED TO TW 8/1/16,Yes
21,http://time.com/,1,ADDED TO TW 8/1/16,No
22,http://thomsonreuters.com/,1,ADDED TO TW 3/17/2017,NaN
23,http://thinkadvisor.com/,1,ADDED TO TW 8/1/16,No
24,http://thestreet.com/,1,ADDED TO TW 8/1/16,No
25,http://therealdeal.com/,1,ADDED TO TW 3/2/2017,NaN
26,http://theatlantic.com/,1,ADDED TO TW 3/2/2017,NaN
27,http://siliconangle.com/,1,ADDED TO TW 3/2/2017,NaN
28,http://seekingalpha.com/,1,ADDED TO TW 8/1/16,No
29,http://sailingworld.com/,1,ADDED TO TW 9/21/16,No
...,...,...,...,...
4807,http://hercules.finance/,3,NaN,NaN
4808,http://dirtdiggersdigest.org/,3,NaN,NaN
4809,http://xm.com/,3,NaN,NaN
4810,http://over25tips.com/,3,NaN,NaN
4811,http://jolome.com/,3,NaN,NaN
4812,http://benefitslink.com/,3,NaN,NaN
4813,http://dailytelescope.com/,3,NaN,NaN
4814,http://oakpark.com/,3,NaN,NaN
4815,http://wallstreetinvestorplace.com/,3,NaN,NaN
4816,http://forwardgeek.com/,3,NaN,NaN
4817,http://dontwasteyourmoney.com/,3,NaN,NaN
4818,http://chinaimportal.com/,3,NaN,NaN
4819,http://usgeometry.us/,3,NaN,NaN
4820,http://000webhostapp.com/,3,NaN,NaN
4821,http://ncsu.edu/,3,NaN,NaN
4822,http://makegameswithus.us/,3,NaN,NaN
4823,http://marklogic.com/,3,NaN,NaN
4824,http://strategiccoin.com/,3,NaN,NaN
4825,http://oakpark.com/,3,NaN,NaN
4826,http://llodo.com/,3,NaN,NaN
4827,http://gr8ambitionz.com/,3,NaN,NaN
4828,http://ivoox.com/,3,NaN,NaN
4829,http://medium.com/,3,NaN,NaN
4830,http://jlvcollegecounseling.com/,3,NaN,NaN
4831,http://feedandgrain.com/,3,NaN,NaN
4832,http://information-management.com/,2,NaN,NaN
4833,http://people.com/,3,NaN,NaN
4834,http://thehardmoneypros.com/,3,NaN,NaN
4835,http://rollcall.com/,3,NaN,NaN
4836,http://opednews.com/,3,NaN,NaN

In [164]:
clean.columns

Index(['domain_url', 'Tier', 'Notes', 'Exact Match?'], dtype='object')

In [165]:
del clean['Tier']
del clean['Notes']
del clean['Exact Match?']

In [166]:
sample=clean.head(10)
sample

                                       domain_url
0                   https://www.entrepreneur.com/
1                            https://next.ft.com/
2                               http://yahoo.com/
3                           http://www.worth.com/
4  http://www.thinkadvisor.com/investment-advisor
5                       http://www.kiplinger.com/
6           http://www.institutionalinvestor.com/
7                             http://www.inc.com/
8                     http://www.foxbusiness.com/
9            http://www.fa-mag.com/private-wealth

In [171]:
a=sample['domain_url'].apply(url_to_call)
print(a)

0    <Response [502]>
1    <Response [200]>
2    <Response [200]>
3    <Response [200]>
4    <Response [502]>
5    <Response [200]>
6    <Response [200]>
7    <Response [200]>
8    <Response [200]>
9    <Response [502]>
Name: domain_url, dtype: object

In [172]:
sample['Response']=a
sample

/Users/riya/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

                                       domain_url          Response  Trash
0                   https://www.entrepreneur.com/  <Response [502]>      1
1                            https://next.ft.com/  <Response [200]>      1
2                               http://yahoo.com/  <Response [200]>      1
3                           http://www.worth.com/  <Response [200]>      1
4  http://www.thinkadvisor.com/investment-advisor  <Response [502]>      1
5                       http://www.kiplinger.com/  <Response [200]>      1
6           http://www.institutionalinvestor.com/  <Response [200]>      1
7                             http://www.inc.com/  <Response [200]>      1
8                     http://www.foxbusiness.com/  <Response [200]>      1
9            http://www.fa-mag.com/private-wealth  <Response [502]>      1

In [181]:
sample['Trash']=""
for Response in sample:
    #if call.status_code==200:
    if Response=="<Response [200]>":
        sample['Trash']='0'
    else:
        sample['Trash']='1'
print(sample)

                                       domain_url          Response Trash
0                   https://www.entrepreneur.com/  <Response [502]>     1
1                            https://next.ft.com/  <Response [200]>     1
2                               http://yahoo.com/  <Response [200]>     1
3                           http://www.worth.com/  <Response [200]>     1
4  http://www.thinkadvisor.com/investment-advisor  <Response [502]>     1
5                       http://www.kiplinger.com/  <Response [200]>     1
6           http://www.institutionalinvestor.com/  <Response [200]>     1
7                             http://www.inc.com/  <Response [200]>     1
8                     http://www.foxbusiness.com/  <Response [200]>     1
9            http://www.fa-mag.com/private-wealth  <Response [502]>     1

/Users/riya/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/Users/riya/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys